version: '3.8'

services:
  db:
    image: postgres:15
    container_name: airdrop_bot_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: airdrop_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: airdrop_bot_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data: